### ISSUE TITLE
Survey with multiple questions

### ISSUE THREAD

**Issue by effettoMapet** [Jefferson49/joomla4_plugin_sexy_polling#103]
HI
I want to create a Survey that has more questions.

Now for each question the 'vote' button appears, while I need to have various questions to answer and then just one 'vote' button.
is it possible to do it?

Thank you all for the important help.
![aaa_1](https://github.com/user-attachments/assets/3b1021c9-71be-47f3-980e-759a0b1cb360)
![aaa_2](https://github.com/user-attachments/assets/9082ac3f-b2ed-4164-a5ab-c98b81d7d0a8)

**Comment by Jefferson49** [comment]
Thanks for the interesting question. I could imagine that it would be possible to work on a template for the votes to get a more horizontal layout with the options (1, 2, 3, ... in your proposal) in a row instead of in a list. This might allow a single poll/question to look like your proposal. However, the current concept does not allow multiple questions within one poll and vote for several questions wiht one vote button. The reason is that the whole data model and database tables are centered around a poll with a single question. Since, I am afraid that the overall concept of your proposal would not be feasible.
