### ISSUE TITLE
"Show Add Answer Icon" switch does not work

### ISSUE THREAD

**Issue by ghost** [Jefferson49/joomla4_plugin_sexy_polling#29]
It looks like the "Show Add Answer Icon" switch does not work. Even if it's switched off I see the option to add a custom answer. All other switches like "Show Scale Icon" or "Show Back Icon" working as expected. (version 4.1.6)

**Comment by Jefferson49** [comment]
Thank you for reporting the issue. I performed a short test and the icon seems to switch on and off as expected, also see screenshot.

![with icon](https://user-images.githubusercontent.com/81484983/216125004-331d1fb6-4499-4088-bb98-fca7f1282aff.JPG)
 
Maybe, it is a misunderstanding. The "Show Add Answer Icon" switch does not define if adding of answers is allowed or not. This is defined by the "Who can add an answer" setting. If this setting is "public", everyone can add an answer. Otherwise, it is restricted to certain user groups.

If this does not answer your question, it might be helpful to post some screenshot.
