### ISSUE TITLE
Module css

### ISSUE THREAD

**Issue by thodorisgo** [Jefferson49/joomla4_plugin_sexy_polling#39]
Using the sexy polls module to display polls is not loading the css correctly.
Instead when using the shortcodes the css is loaded corectly.

**Comment by Jefferson49** [comment]
Can you explain this in more detail? Do you observe this with templates in the administrators backend? Or do you add some css classes to the module (also in admin backend). Or the template layout (or its css) not loading in the user frontend?

**Comment by thodorisgo** [comment]
While trying to display a poll by using your module there is no styling at all. But if i use a custom module with polls shortcode the styling is correct.

**Comment by Jefferson49** [comment]
> While trying to display a poll by using your module there is no styling at all

Can you post an example URL for this behaviour? Does it mean you only see the raw text without any styling? In the URL, you shared in the other issue, the styling looked fine.

**Comment by thodorisgo** [comment]
Yes that's exactly the issue. The link i shared has the poll loaded through shortcode.
In case you can't reproduce it i can share a link to check for your self

**Comment by Jefferson49** [comment]
Some further questions, just to be sure that we are talking about the same thing:
- If you talk about using a custom module, you got to Modules / New and select the module type "Custom". Afterwards you put some code into the custom module in order to include the "Sexy Polling Reloaded" plugin
- If you talk about using it "as a module", you go to Modules / New and select the module type "Sexy Polling Reloaded" directly

Is my understanding correct?

I have no experiences about custom modules and the combination with sexy polling. I guess that the vast majority of users is using sexy polling just as a module and I have no feedback about CSS issues or not showing the layout. On my own website and other test environments it works fine. Therefore, it is surprising that it does not work for you and - on the other hand - works as a custom module, which seems to be more challenging in general.

Can you check if you are facing the same behavior with another template? Maybe, the issue is related to your specific template?

For me, it is difficult to analyse further on this issue. I do not know if it is possible for you, but it would help if you could create an example and post the URL in order to have a look at it.

**Comment by thodorisgo** [comment]
Hey Jefferson here you can see the issue live
https://tinyurl.com/sexypoll2
please let me know when you check it so i can unpublish it.

**Comment by Jefferson49** [comment]
Thank you for providing the URL; this really helps a lot!

What I can see:
+ If sexy polling is used as a custom module on your site (and also as a module in my own installation), the CSS is located at: /components/com_sexypolling/assets/css/main.css and /components/com_sexypolling/generate.css
- If sexy polling is used as a module on your site, the CSS is located at: **/media/t4/optimize/css/b9e243627fb2df473e4956bc319ec17d.css**

Therefore, there seems to be some modification to the CSS if used as a module in the T4 framework. On the [T4 framework website](https://www.joomlart.com/t4-framework), I found a statement that _"CSS and JS optimization options help compress almost all the template's CSS and Javascripts and relevant Joomla's files to improve website performance."_

My interpretation of the observed behavior is that the T4 framework takes the initial CSS, optimizes it in some way, and afterwards saves a modified CSS into /media/t4/optimize/css/. Maybe, if using sexy polling as a custom module, T4 will have no code implemented to optimize custom modules. In this case, no optimization seems to happen and the original CSS stays in place.

You might want to have a look at the configuration of the T4 framework on your website. Maybe, there are some configuration parameters to influence the CSS optimization. If not, you might probably have to continue with using sexy polling as a custom module.

**Comment by thodorisgo** [comment]
Yes there is an option to exclude specific css files from being copressed. i added there the generate.css and now it loads the css as it should via the module.
Really sorry for bothering with issues that are caused by T4 framework. If i find any bug in the future i will try to check first if it's related to T4.
Thank you

**Comment by Jefferson49** [comment]
No problem; I am happy that you could solve the issue. For me, it is interesting to learn about different scenarios how the plugin is used.

**Comment by Jefferson49** [comment]
One additional question: I guess you are using a Greek frontend translation for sexy polling. If it were o.k. for you, it might be possible to contribute the translation to the next release, which I plan in the next week. For the frontend, this is the following file:
\components\com_sexypolling\language\el-GR\el-GR.com_sexypolling.ini

You can just attach the file to a (new) issue.

**Comment by thodorisgo** [comment]
With pleasure i will share my translation. 
PS: The path you provided is wrong. The tanslations are on the folder language on root folder and in my case \language\el-GR\el-GR.com_sexypolling.ini
