### ISSUE TITLE
Confirmation of technical requirements

### ISSUE THREAD

**Issue by 4creator** [Jefferson49/joomla4_plugin_sexy_polling#84]
Hello,

I have noticed that the pace of Joomla development has been quite rapid recently, and I am concerned about compatibility with our server environment.

Currently, we are running Joomla 4 on a server environment with CentOS 7, MySQL 5.7, and PHP versions 7.4. However, we plan to migrate to **AlmaLinux 8**, **MySQL 8**, **PHP 8.2** soon. 
Could this migration potentially affect the behavior of Sexy Polling Reloaded?

Additionally, it would be beneficial if we could confirm the technical requirements for Sexy Polling Reloaded, considering a future upgrade to Joomla 5.

Regards

**Comment by Jefferson49** [comment]
>  it would be beneficial if we could confirm the technical requirements for Sexy Polling Reloaded, considering a future upgrade to Joomla 5.

Currently, I am maintaining 2 branches (5.0.x and 5.1.x). The 5.1. branch is already fully compatible with Joomla 5, even without backward compatibility module. The download of the latest version is available here: [v5.1.2](https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/releases/tag/v5.1.2).

Since you are working on Joomla 4, you can already switch to the v5.1.2 version, since the 5.1 branch can be used for Joomla 4 and Joomla 5. The 5.0 branch is suitable for Joomla 3 and 4; it is mainly needed for Joomla 3 users and for Joomla 3=>4 migration.

Currently, I am applying all changes to both of the branches.

**Comment by 4creator** [comment]
I appreciate the information regarding the compatibility of Sexy Polling Reloaded with Joomla 4 and 5, as well as the guidance towards using version 5.1.2. 

Is it safe to assume that the behavior of Sexy Polling Reloaded will not be affected by changes in PHP and MySQL versions?

**Comment by Jefferson49** [comment]
> Is it safe to assume that the behavior of Sexy Polling Reloaded will not be affected by changes in PHP and MySQL versions?

I try to align to the Joomla recommendations. However, I can not test the full bandwidth:
- [Technical Requirements Joomla 5](https://manual.joomla.org/docs/next/get-started/technical-requirements/)
- [Technical Requirements Joomla 3, 4](https://manual.joomla.org/docs/4.4/get-started/technical-requirements/) 

In my own environment. I test with the following setup:
- Joomla 4/5: PHP 8.2, MariaDB 10.11.2 (MySQL 8.0.32, mysqli 8.2.5)
- Joomla 3: PHP 8.0, same database

There was a major change between PHP 7 and PHP 8. Since PHP 8, I did not face any PHP issues. 

There were some database issues with sexy polling, which could not be fully clarifyed: https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/issues/46, https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/issues/49, https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/issues/50, https://github.com/Jefferson49/Joomla_plugin_sexypolling_reloaded/issues/58. 
However, after changing the database installation script starting with version 5.0/5.1, there were no issues reported any more.

In general: There might exist some risk with downgrading to something like MySQL 5.6 and PHP 7. Currently, I do not know any issues with upgrading to new MySQL 8.x versions and PHP 8.x versions.

**Comment by 4creator** [comment]
> In my own environment. I test with the following setup:
> Joomla 4/5: PHP 8.2, MySQL 8.2.5

From what I infer from your response, it looks like there is no problem in my case. 
Thank you for the useful information.
